#' Example Oyster Journey History File
#'
#' An example of a single month's journey history data received originally as
#' a CSV from Transport for London. Location names replaced.
#'
#' @docType data
#'
#' @usage data(oy_history)
#'
#' @format An object of class \code{"dataframe"}.
#'
#' @keywords datasets
#'
#' @references Generated by and received from (\href{https://tfl.gov.uk/}{Transport for London}).
#'
#' @source \href{https://tfl.gov.uk/}{Transport for London}.
#'
#' @examples
#' data(oy_history)
"oy_history"
